// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/order/order.proto

package orderpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order_Status int32

const (
	Order_ACTIVE  Order_Status = 0
	Order_DELETED Order_Status = 1
	Order_FILLED  Order_Status = 2
)

var Order_Status_name = map[int32]string{
	0: "ACTIVE",
	1: "DELETED",
	2: "FILLED",
}

var Order_Status_value = map[string]int32{
	"ACTIVE":  0,
	"DELETED": 1,
	"FILLED":  2,
}

func (x Order_Status) String() string {
	return proto.EnumName(Order_Status_name, int32(x))
}

func (Order_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{0, 0}
}

type HandleOrderRequest_Action int32

const (
	HandleOrderRequest_NEW    HandleOrderRequest_Action = 0
	HandleOrderRequest_MODIFY HandleOrderRequest_Action = 1
	HandleOrderRequest_DELETE HandleOrderRequest_Action = 2
)

var HandleOrderRequest_Action_name = map[int32]string{
	0: "NEW",
	1: "MODIFY",
	2: "DELETE",
}

var HandleOrderRequest_Action_value = map[string]int32{
	"NEW":    0,
	"MODIFY": 1,
	"DELETE": 2,
}

func (x HandleOrderRequest_Action) String() string {
	return proto.EnumName(HandleOrderRequest_Action_name, int32(x))
}

func (HandleOrderRequest_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{1, 0}
}

type HandleOrderResponse_Response int32

const (
	HandleOrderResponse_OK    HandleOrderResponse_Response = 0
	HandleOrderResponse_ERROR HandleOrderResponse_Response = 1
)

var HandleOrderResponse_Response_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var HandleOrderResponse_Response_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x HandleOrderResponse_Response) String() string {
	return proto.EnumName(HandleOrderResponse_Response_name, int32(x))
}

func (HandleOrderResponse_Response) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{2, 0}
}

type Order struct {
	UUID                 string               `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	InstrumentKey        string               `protobuf:"bytes,3,opt,name=instrument_key,json=instrumentKey,proto3" json:"instrument_key,omitempty"`
	Currency             string               `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Size                 float32              `protobuf:"fixed32,5,opt,name=size,proto3" json:"size,omitempty"`
	Price                float32              `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	Created              *timestamp.Timestamp `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Status               Order_Status         `protobuf:"varint,8,opt,name=status,proto3,enum=order.Order_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Order) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Order) GetInstrumentKey() string {
	if m != nil {
		return m.InstrumentKey
	}
	return ""
}

func (m *Order) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Order) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Order) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Order) GetStatus() Order_Status {
	if m != nil {
		return m.Status
	}
	return Order_ACTIVE
}

type HandleOrderRequest struct {
	Order                *Order                    `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Action               HandleOrderRequest_Action `protobuf:"varint,2,opt,name=action,proto3,enum=order.HandleOrderRequest_Action" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *HandleOrderRequest) Reset()         { *m = HandleOrderRequest{} }
func (m *HandleOrderRequest) String() string { return proto.CompactTextString(m) }
func (*HandleOrderRequest) ProtoMessage()    {}
func (*HandleOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{1}
}

func (m *HandleOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleOrderRequest.Unmarshal(m, b)
}
func (m *HandleOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleOrderRequest.Marshal(b, m, deterministic)
}
func (m *HandleOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleOrderRequest.Merge(m, src)
}
func (m *HandleOrderRequest) XXX_Size() int {
	return xxx_messageInfo_HandleOrderRequest.Size(m)
}
func (m *HandleOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HandleOrderRequest proto.InternalMessageInfo

func (m *HandleOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *HandleOrderRequest) GetAction() HandleOrderRequest_Action {
	if m != nil {
		return m.Action
	}
	return HandleOrderRequest_NEW
}

type HandleOrderResponse struct {
	Response             HandleOrderResponse_Response `protobuf:"varint,1,opt,name=response,proto3,enum=order.HandleOrderResponse_Response" json:"response,omitempty"`
	ErrorMessage         string                       `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *HandleOrderResponse) Reset()         { *m = HandleOrderResponse{} }
func (m *HandleOrderResponse) String() string { return proto.CompactTextString(m) }
func (*HandleOrderResponse) ProtoMessage()    {}
func (*HandleOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{2}
}

func (m *HandleOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandleOrderResponse.Unmarshal(m, b)
}
func (m *HandleOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandleOrderResponse.Marshal(b, m, deterministic)
}
func (m *HandleOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandleOrderResponse.Merge(m, src)
}
func (m *HandleOrderResponse) XXX_Size() int {
	return xxx_messageInfo_HandleOrderResponse.Size(m)
}
func (m *HandleOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HandleOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HandleOrderResponse proto.InternalMessageInfo

func (m *HandleOrderResponse) GetResponse() HandleOrderResponse_Response {
	if m != nil {
		return m.Response
	}
	return HandleOrderResponse_OK
}

func (m *HandleOrderResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ValidateOrderRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateOrderRequest) Reset()         { *m = ValidateOrderRequest{} }
func (m *ValidateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateOrderRequest) ProtoMessage()    {}
func (*ValidateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{3}
}

func (m *ValidateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateOrderRequest.Unmarshal(m, b)
}
func (m *ValidateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateOrderRequest.Marshal(b, m, deterministic)
}
func (m *ValidateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateOrderRequest.Merge(m, src)
}
func (m *ValidateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateOrderRequest.Size(m)
}
func (m *ValidateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateOrderRequest proto.InternalMessageInfo

func (m *ValidateOrderRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type ValidateOrderResponse struct {
	Valid                bool     `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateOrderResponse) Reset()         { *m = ValidateOrderResponse{} }
func (m *ValidateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateOrderResponse) ProtoMessage()    {}
func (*ValidateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_57fe01adccda313b, []int{4}
}

func (m *ValidateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateOrderResponse.Unmarshal(m, b)
}
func (m *ValidateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateOrderResponse.Marshal(b, m, deterministic)
}
func (m *ValidateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateOrderResponse.Merge(m, src)
}
func (m *ValidateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateOrderResponse.Size(m)
}
func (m *ValidateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateOrderResponse proto.InternalMessageInfo

func (m *ValidateOrderResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidateOrderResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("order.Order_Status", Order_Status_name, Order_Status_value)
	proto.RegisterEnum("order.HandleOrderRequest_Action", HandleOrderRequest_Action_name, HandleOrderRequest_Action_value)
	proto.RegisterEnum("order.HandleOrderResponse_Response", HandleOrderResponse_Response_name, HandleOrderResponse_Response_value)
	proto.RegisterType((*Order)(nil), "order.Order")
	proto.RegisterType((*HandleOrderRequest)(nil), "order.HandleOrderRequest")
	proto.RegisterType((*HandleOrderResponse)(nil), "order.HandleOrderResponse")
	proto.RegisterType((*ValidateOrderRequest)(nil), "order.ValidateOrderRequest")
	proto.RegisterType((*ValidateOrderResponse)(nil), "order.ValidateOrderResponse")
}

func init() { proto.RegisterFile("api/order/order.proto", fileDescriptor_57fe01adccda313b) }

var fileDescriptor_57fe01adccda313b = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xe1, 0x8a, 0xd3, 0x5c,
	0x10, 0x6d, 0xb2, 0x9b, 0xb4, 0x9d, 0x6e, 0x4b, 0xb8, 0x6d, 0x21, 0x5f, 0x3e, 0xc5, 0x92, 0x45,
	0xa8, 0x88, 0x29, 0x44, 0x7f, 0x88, 0x7f, 0x64, 0xb5, 0x29, 0x96, 0xed, 0x5a, 0xb8, 0xdb, 0x5d,
	0x51, 0x90, 0x25, 0x6d, 0xc7, 0x12, 0x6c, 0x93, 0x78, 0x73, 0xbb, 0x50, 0x1f, 0x45, 0xf0, 0x1d,
	0x7c, 0x44, 0xc9, 0xdc, 0xb4, 0xee, 0x6a, 0x17, 0xf4, 0x4f, 0x99, 0x39, 0x73, 0x66, 0xce, 0xcc,
	0xe9, 0x0d, 0xb4, 0xc3, 0x34, 0xea, 0x25, 0x62, 0x8e, 0x42, 0xfd, 0x7a, 0xa9, 0x48, 0x64, 0xc2,
	0x0c, 0x4a, 0x9c, 0x07, 0x8b, 0x24, 0x59, 0x2c, 0xb1, 0x47, 0xe0, 0x74, 0xfd, 0xa9, 0x27, 0xa3,
	0x15, 0x66, 0x32, 0x5c, 0xa5, 0x8a, 0xe7, 0xfe, 0xd0, 0xc1, 0x18, 0xe7, 0x54, 0xc6, 0xe0, 0xf0,
	0xe2, 0x62, 0xd8, 0xb7, 0xb5, 0x8e, 0xd6, 0xad, 0x72, 0x8a, 0x59, 0x0b, 0x0c, 0x5c, 0x85, 0xd1,
	0xd2, 0xd6, 0x09, 0x54, 0x09, 0x7b, 0x08, 0x8d, 0x28, 0xce, 0xa4, 0x58, 0xaf, 0x30, 0x96, 0x57,
	0x9f, 0x71, 0x63, 0x1f, 0x50, 0xb9, 0xfe, 0x0b, 0x3d, 0xc5, 0x0d, 0x73, 0xa0, 0x32, 0x5b, 0x0b,
	0x81, 0xf1, 0x6c, 0x63, 0x1f, 0x12, 0x61, 0x97, 0xe7, 0x62, 0x59, 0xf4, 0x15, 0x6d, 0xa3, 0xa3,
	0x75, 0x75, 0x4e, 0x71, 0x2e, 0x96, 0x8a, 0x68, 0x86, 0xb6, 0x49, 0xa0, 0x4a, 0xd8, 0x33, 0x28,
	0xcf, 0x04, 0x86, 0x12, 0xe7, 0x76, 0xb9, 0xa3, 0x75, 0x6b, 0xbe, 0xe3, 0xa9, 0x9b, 0xbc, 0xed,
	0x4d, 0xde, 0x64, 0x7b, 0x13, 0xdf, 0x52, 0xd9, 0x63, 0x30, 0x33, 0x19, 0xca, 0x75, 0x66, 0x57,
	0x3a, 0x5a, 0xb7, 0xe1, 0x37, 0x3d, 0x65, 0x0e, 0x9d, 0xea, 0x9d, 0x53, 0x89, 0x17, 0x14, 0xf7,
	0x09, 0x98, 0x0a, 0x61, 0x00, 0xe6, 0xc9, 0xeb, 0xc9, 0xf0, 0x32, 0xb0, 0x4a, 0xac, 0x06, 0xe5,
	0x7e, 0x30, 0x0a, 0x26, 0x41, 0xdf, 0xd2, 0xf2, 0xc2, 0x60, 0x38, 0x1a, 0x05, 0x7d, 0x4b, 0x77,
	0xbf, 0x6b, 0xc0, 0xde, 0x84, 0xf1, 0x7c, 0x89, 0x34, 0x8d, 0xe3, 0x97, 0x35, 0x66, 0x92, 0xb9,
	0xa0, 0x3c, 0x27, 0x03, 0x6b, 0xfe, 0xd1, 0x4d, 0x45, 0xae, 0x4a, 0xec, 0x39, 0x98, 0xe1, 0x4c,
	0x46, 0x49, 0x4c, 0x86, 0x36, 0xfc, 0x4e, 0x41, 0xfa, 0x73, 0x9c, 0x77, 0x42, 0x3c, 0x5e, 0xf0,
	0xdd, 0x47, 0x60, 0x2a, 0x84, 0x95, 0xe1, 0xe0, 0x6d, 0xf0, 0xce, 0x2a, 0xe5, 0x3b, 0x9d, 0x8d,
	0xfb, 0xc3, 0xc1, 0x7b, 0xb5, 0x9f, 0x5a, 0xd6, 0xd2, 0xdd, 0x6f, 0x1a, 0x34, 0x6f, 0x0d, 0xcc,
	0xd2, 0x24, 0xce, 0x90, 0xbd, 0x84, 0x8a, 0x28, 0x62, 0xda, 0xb1, 0xe1, 0x1f, 0xef, 0x93, 0x57,
	0x0c, 0x6f, 0x1b, 0xf0, 0x5d, 0x13, 0x3b, 0x86, 0x3a, 0x0a, 0x91, 0x88, 0xab, 0x15, 0x66, 0x59,
	0xb8, 0xc0, 0xe2, 0x55, 0x1c, 0x11, 0x78, 0xa6, 0x30, 0xf7, 0x3e, 0x54, 0x76, 0x8a, 0x26, 0xe8,
	0xe3, 0x53, 0xab, 0xc4, 0xaa, 0x60, 0x04, 0x9c, 0x8f, 0xb9, 0xa5, 0xb9, 0x2f, 0xa0, 0x75, 0x19,
	0x2e, 0xa3, 0x79, 0x28, 0xff, 0xd9, 0x3d, 0x97, 0x43, 0xfb, 0xb7, 0xde, 0x42, 0xa7, 0x05, 0xc6,
	0x75, 0x5e, 0xa0, 0xe6, 0x0a, 0x57, 0xc9, 0x5f, 0xad, 0xeb, 0x7f, 0x84, 0x26, 0xcd, 0x52, 0x16,
	0x88, 0x73, 0x14, 0xd7, 0xf9, 0xab, 0x1b, 0x40, 0xed, 0x86, 0x29, 0xec, 0xbf, 0x3b, 0xff, 0x27,
	0xc7, 0xb9, 0xdb, 0x43, 0xb7, 0xe4, 0x23, 0xb4, 0x09, 0x2a, 0xf6, 0x4e, 0x76, 0x02, 0x23, 0xa8,
	0xdf, 0xba, 0x85, 0xfd, 0x5f, 0xcc, 0xd9, 0xe7, 0x8e, 0x73, 0x6f, 0x7f, 0x71, 0x2b, 0xf3, 0xaa,
	0xfa, 0xa1, 0x4c, 0x84, 0x74, 0x3a, 0x35, 0xe9, 0xb3, 0x78, 0xfa, 0x33, 0x00, 0x00, 0xff, 0xff,
	0x93, 0x0d, 0x6a, 0x8e, 0x18, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderHandlerServiceClient is the client API for OrderHandlerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderHandlerServiceClient interface {
	HandleOrder(ctx context.Context, in *HandleOrderRequest, opts ...grpc.CallOption) (*HandleOrderResponse, error)
}

type orderHandlerServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderHandlerServiceClient(cc *grpc.ClientConn) OrderHandlerServiceClient {
	return &orderHandlerServiceClient{cc}
}

func (c *orderHandlerServiceClient) HandleOrder(ctx context.Context, in *HandleOrderRequest, opts ...grpc.CallOption) (*HandleOrderResponse, error) {
	out := new(HandleOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderHandlerService/HandleOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderHandlerServiceServer is the server API for OrderHandlerService service.
type OrderHandlerServiceServer interface {
	HandleOrder(context.Context, *HandleOrderRequest) (*HandleOrderResponse, error)
}

// UnimplementedOrderHandlerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderHandlerServiceServer struct {
}

func (*UnimplementedOrderHandlerServiceServer) HandleOrder(ctx context.Context, req *HandleOrderRequest) (*HandleOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleOrder not implemented")
}

func RegisterOrderHandlerServiceServer(s *grpc.Server, srv OrderHandlerServiceServer) {
	s.RegisterService(&_OrderHandlerService_serviceDesc, srv)
}

func _OrderHandlerService_HandleOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderHandlerServiceServer).HandleOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderHandlerService/HandleOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderHandlerServiceServer).HandleOrder(ctx, req.(*HandleOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderHandlerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderHandlerService",
	HandlerType: (*OrderHandlerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleOrder",
			Handler:    _OrderHandlerService_HandleOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/order/order.proto",
}

// OrderValidatorServiceClient is the client API for OrderValidatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderValidatorServiceClient interface {
	ValidateOrder(ctx context.Context, in *ValidateOrderRequest, opts ...grpc.CallOption) (*ValidateOrderResponse, error)
}

type orderValidatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderValidatorServiceClient(cc *grpc.ClientConn) OrderValidatorServiceClient {
	return &orderValidatorServiceClient{cc}
}

func (c *orderValidatorServiceClient) ValidateOrder(ctx context.Context, in *ValidateOrderRequest, opts ...grpc.CallOption) (*ValidateOrderResponse, error) {
	out := new(ValidateOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderValidatorService/ValidateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderValidatorServiceServer is the server API for OrderValidatorService service.
type OrderValidatorServiceServer interface {
	ValidateOrder(context.Context, *ValidateOrderRequest) (*ValidateOrderResponse, error)
}

// UnimplementedOrderValidatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderValidatorServiceServer struct {
}

func (*UnimplementedOrderValidatorServiceServer) ValidateOrder(ctx context.Context, req *ValidateOrderRequest) (*ValidateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateOrder not implemented")
}

func RegisterOrderValidatorServiceServer(s *grpc.Server, srv OrderValidatorServiceServer) {
	s.RegisterService(&_OrderValidatorService_serviceDesc, srv)
}

func _OrderValidatorService_ValidateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderValidatorServiceServer).ValidateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderValidatorService/ValidateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderValidatorServiceServer).ValidateOrder(ctx, req.(*ValidateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderValidatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderValidatorService",
	HandlerType: (*OrderValidatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateOrder",
			Handler:    _OrderValidatorService_ValidateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/order/order.proto",
}
