// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/price/price.proto

package pricepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Price struct {
	InstrumentKey        string   `protobuf:"bytes,1,opt,name=instrumentKey,proto3" json:"instrumentKey,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Price) Reset()         { *m = Price{} }
func (m *Price) String() string { return proto.CompactTextString(m) }
func (*Price) ProtoMessage()    {}
func (*Price) Descriptor() ([]byte, []int) {
	return fileDescriptor_48f266350c2d41c6, []int{0}
}

func (m *Price) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Price.Unmarshal(m, b)
}
func (m *Price) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Price.Marshal(b, m, deterministic)
}
func (m *Price) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Price.Merge(m, src)
}
func (m *Price) XXX_Size() int {
	return xxx_messageInfo_Price.Size(m)
}
func (m *Price) XXX_DiscardUnknown() {
	xxx_messageInfo_Price.DiscardUnknown(m)
}

var xxx_messageInfo_Price proto.InternalMessageInfo

func (m *Price) GetInstrumentKey() string {
	if m != nil {
		return m.InstrumentKey
	}
	return ""
}

func (m *Price) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetAllPricesResponse struct {
	Prices               []*Price `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPricesResponse) Reset()         { *m = GetAllPricesResponse{} }
func (m *GetAllPricesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPricesResponse) ProtoMessage()    {}
func (*GetAllPricesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_48f266350c2d41c6, []int{1}
}

func (m *GetAllPricesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPricesResponse.Unmarshal(m, b)
}
func (m *GetAllPricesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPricesResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPricesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPricesResponse.Merge(m, src)
}
func (m *GetAllPricesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPricesResponse.Size(m)
}
func (m *GetAllPricesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPricesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPricesResponse proto.InternalMessageInfo

func (m *GetAllPricesResponse) GetPrices() []*Price {
	if m != nil {
		return m.Prices
	}
	return nil
}

func init() {
	proto.RegisterType((*Price)(nil), "price.Price")
	proto.RegisterType((*GetAllPricesResponse)(nil), "price.GetAllPricesResponse")
}

func init() { proto.RegisterFile("api/price/price.proto", fileDescriptor_48f266350c2d41c6) }

var fileDescriptor_48f266350c2d41c6 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4d, 0x2c, 0xc8, 0xd4,
	0x2f, 0x28, 0xca, 0x4c, 0x4e, 0x85, 0x90, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60,
	0x8e, 0x94, 0x74, 0x7a, 0x7e, 0x7e, 0x7a, 0x0e, 0x48, 0x2a, 0xbf, 0x24, 0x3f, 0xa9, 0x34, 0x4d,
	0x3f, 0x35, 0xb7, 0xa0, 0xa4, 0x12, 0xa2, 0x46, 0xc9, 0x99, 0x8b, 0x35, 0x00, 0xa4, 0x4a, 0x48,
	0x85, 0x8b, 0x37, 0x33, 0xaf, 0xb8, 0xa4, 0xa8, 0x34, 0x37, 0x35, 0xaf, 0xc4, 0x3b, 0xb5, 0x52,
	0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x55, 0x50, 0x48, 0x84, 0x0b, 0x62, 0xa8, 0x04, 0x93,
	0x02, 0xa3, 0x06, 0x53, 0x10, 0x84, 0xa3, 0x64, 0xc3, 0x25, 0xe2, 0x9e, 0x5a, 0xe2, 0x98, 0x93,
	0x03, 0x36, 0xaa, 0x38, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x18, 0x64, 0x26, 0x1b, 0x58, 0x41,
	0xb1, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x11, 0x8f, 0x1e, 0xc4, 0x79, 0x60, 0x65, 0x41, 0x50,
	0x39, 0xa3, 0x30, 0x2e, 0x1e, 0xb0, 0x40, 0x70, 0x6a, 0x51, 0x19, 0xc8, 0x25, 0x6e, 0x5c, 0xbc,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x10, 0xe3, 0x84, 0xc4, 0xf4, 0x20, 0x3e, 0xd0, 0x83,
	0xf9, 0x40, 0xcf, 0x15, 0xe4, 0x03, 0x29, 0x69, 0xa8, 0x71, 0xd8, 0xec, 0x56, 0x62, 0x70, 0xe2,
	0x8c, 0x62, 0x07, 0xcb, 0x17, 0x24, 0x25, 0xb1, 0x81, 0x75, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x50, 0x3a, 0x92, 0x64, 0x29, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PriceServiceClient interface {
	RequestPrices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllPricesResponse, error)
}

type priceServiceClient struct {
	cc *grpc.ClientConn
}

func NewPriceServiceClient(cc *grpc.ClientConn) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) RequestPrices(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetAllPricesResponse, error) {
	out := new(GetAllPricesResponse)
	err := c.cc.Invoke(ctx, "/price.PriceService/RequestPrices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PriceServiceServer is the server API for PriceService service.
type PriceServiceServer interface {
	RequestPrices(context.Context, *empty.Empty) (*GetAllPricesResponse, error)
}

// UnimplementedPriceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPriceServiceServer struct {
}

func (*UnimplementedPriceServiceServer) RequestPrices(ctx context.Context, req *empty.Empty) (*GetAllPricesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPrices not implemented")
}

func RegisterPriceServiceServer(s *grpc.Server, srv PriceServiceServer) {
	s.RegisterService(&_PriceService_serviceDesc, srv)
}

func _PriceService_RequestPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PriceServiceServer).RequestPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/price.PriceService/RequestPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PriceServiceServer).RequestPrices(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _PriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "price.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPrices",
			Handler:    _PriceService_RequestPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/price/price.proto",
}
